title: Aymen Mohamed
logo: assets/img/Circle_Headshot.png
description: Passionate Data Scientist looking to spur innovation and derive data-driven insights at any which way!
#show_downloads: true
theme: jekyll-theme-minimal
